---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: centos-6.5
  run_list: ['recipe[yum-epel]']
  driver_config:
    box: opscode-centos-6.5
    customize:
      cpus: 2
      memory: 512
- name: ubuntu-12.04
  run_list: ['recipe[apt]']
  driver_config:
    box: opscode-ubuntu-12.04
    customize:
      cpus: 2
      memory: 512
- name: ubuntu-14.04
  run_list: ['recipe[apt]']
  driver_config:
    box: opscode-ubuntu-14.04
    customize:
      cpus: 2
      memory: 512

suites:
- name: master
  run_list:
  - recipe[client-rs-mysql::master]
  provisioner:
      solo_rb:
        log_location: /var/log/chef-solo.log
  attributes:
    cloud:
      provider: 'vagrant'
      public_ips: ['10.10.1.1']
      private_ips: ['10.0.2.15']
    rs-mysql:
      dns:
        master_fqdn: 'www.test.com'
        user_key: <%= ENV['DNS_USER_KEY'] %>
        secret_key: <%= ENV['DNS_SECRET_KEY'] %>
      backup:
        lineage: 'lineage'
      server_root_password: rootpass
      server_repl_password: replpass
      server_usage: dedicated
    rightscale:
      instance_uuid: '1111111'
